numbers = [1, 2]
print(numbers[2])

# An exception is a kind of error that terminates the execution of a program.
# This statement(line) threw an exception. - изключение

# This is an example of an exception
# That was thrown because of a programmer's mistake.


# Another example: 

age = int(input('Age: '))